name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: [self-hosted, Linux, X64, splitux]
    name: Build x86_64

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build libsdl2-dev libevdev-dev patchelf

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir build && cd build
          cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Prepare release artifacts
        run: |
          cd build
          strip gptokeyb2
          tar -czvf gptokeyb-splitux-${{ github.ref_name }}.tar.gz gptokeyb2 lib/libinterpose.so

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/gptokeyb-splitux-*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
